#!/bin/bash
# Set the filename
filename='db.sqlite3'
# Create an empty file
touch $filename
# Check the file is exists or not
if [ -f $filename ]; then
   rm db.sqlite3
   echo "$filename is removed"
fi

rm -R dump.rdb&redis-cli flushall&redis-cli flushdb&python manage.py migrate
