#!/bin/bash
 redis-server --port 6380 --slaveof 127.0.0.1 6379&python manage.py privatemessages_start&python manage.py comments_start&python manage.py wall_start&gunicorn app.wsgi:application --bind 192.168.1.137:8888
