#!/bin/bash
# source venv/bin/activate & 
redis-server --port 6380 --slaveof 127.0.0.1 6379&python manage.py privatemessages_start&python manage.py comments_start&python manage.py wall_start&/media/sadko/1b32d2c7-3fcf-4c94-ad20-4fb130a7a7d4/PLAYGROUND/social-network/venv/bin/gunicorn app.wsgi:application --bind 192.168.1.50:8888
